env: "local" # local, dev, prod'

http_server:
  address: "localhost:8082"
  timeout: 4s #выделенное время на обработку и ответ на запрос пользователя
  idle_timeout: 60s #время ожидания повторного запроса для клиента

database:
  user: "postgres"
  password: "cbvbcv"
  name: "task_api"
  host: "localhost"
  port: 5433
  url: "postgres://postgres:cbvcbv@localhost:5433/task_api"

auth:
  jwt_secret: "super_secret_key"
  access_token_ttl: "15m"
  refresh_token_ttl: "168h"